// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewClass struct {
	Class   string `json:"class"`
	Section string `json:"section"`
}

type NewMarks struct {
	SubjectName  string   `json:"subject_name"`
	MarksAcq     *int     `json:"marks_acq,omitempty"`
	SubjectMarks *int     `json:"subject_marks,omitempty"`
	Percentage   *float64 `json:"percentage,omitempty"`
}

type NewParent struct {
	Name    string  `json:"name"`
	PhoneNo int     `json:"phone_no"`
	Job     *string `json:"job,omitempty"`
}

type NewStaff struct {
	StaffName string `json:"staff_name"`
	Position  string `json:"position"`
}

type NewStudent struct {
	StudentName string `json:"student_name"   bson:"id"`
	Gender      string `json:"gender"`
	PhoneNo     int    `json:"phone_no"`
	RollNo      string `json:"roll_no"`
	FeePayed    bool   `json:"fee_payed"`
}

type NewSubject struct {
	Subject string `json:"subject"`
	Marks   *int   `json:"marks,omitempty"`
	Class   string `json:"class"`
}

type Student struct {
	ID          string   `json:"id"`
	StudentName string   `json:"student_name"`
	Gender      string   `json:"gender"`
	PhoneNo     int      `json:"phone_no"`
	RollNo      string   `json:"roll_no"`
	FeePayed    bool     `json:"fee_payed"`
	Class       *Classes `json:"class"`
}

type Classes struct {
	ID          string      `json:"id"`
	Class       string      `json:"class"`
	Section     string      `json:"section"`
	Subjects    []*Subjects `json:"subjects,omitempty"`
	StudentsAll []*Student  `json:"students_all,omitempty"`
	Marks       *Marks      `json:"marks,omitempty"`
}

type Marks struct {
	ID           string    `json:"id"`
	Subject      *Subjects `json:"subject"`
	MarksAcq     *int      `json:"marks_acq,omitempty"`
	SubjectMarks *int      `json:"subject_marks,omitempty"`
	Percentage   *float64  `json:"percentage,omitempty"`
}

type Parent struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	PhoneNo int       `json:"phone_no"`
	Job     *string   `json:"job,omitempty"`
	Spous   []*Parent `json:"spous,omitempty"`
}

type Staff struct {
	ID           string     `json:"id"`
	StaffName    string     `json:"staff_name"`
	Position     string     `json:"position"`
	ClassAlloted []*Classes `json:"class_alloted"`
}

type Subjects struct {
	ID         string     `json:"id"`
	Subject    string     `json:"subject"`
	Marks      *int       `json:"marks,omitempty"`
	Class      string     `json:"class"`
	StudentAll []*Student `json:"student_all,omitempty"`
}
