name: setup-graphQL
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs }}
      - run: echo "${{ secrets.MONGODB_URL }}"
